### ISSUE TITLE
Hash given here differs from hash in nnhash.py?

### ISSUE THREAD

**Issue by lambdaTotoro** [anishathalye/neural-hash-collider#4]
I have the following two images:

<img width="250" src="https://user-images.githubusercontent.com/1606110/130304446-743c5755-2b71-417f-b35a-7ed79b98eae1.png"></img> <img width="250" src="https://user-images.githubusercontent.com/1606110/130304433-9092990d-7f08-45b1-9367-c6f4d33ef503.png"></img>

I then ask `nnhash.py` from [AsuharietYgvar/AppleNeuralHash2ONNX](https://github.com/AsuharietYgvar/AppleNeuralHash2ONNX) for the NeuralHash of the second picture (as instructed by the README in this repo) and get a result.

```console
$ python3 nnhash.py model.onnx neuralhash_128x96_seed1.dat ../images/target/palpatine_square.png 
e34b2da852103c3c0828fbd1
```
I then run the collider as instructed with that result as target hash and seem to find a collision:
```console
$ python3 collide.py --image ../images/source/picard_square.png --target e34b2da852103c3c0828fbd1
[.../snip/...]
iteration: 221/1000, best: 0, hash: e34b2da852103c3c0828fbd1, distance: 0, loss: 7.484
```
<img width="250" src="https://user-images.githubusercontent.com/1606110/130305352-2be4e559-a14e-440d-800d-37ca54581f3e.png"></img>
Seems like everything worked fine, the hash displayed is equal to the target!
But! If I now run `nnhash.py` on one of the saved pictures, it gives me a slightly different hash than the target?
```console
$ python3 nnhash.py model.onnx neuralhash_128x96_seed1.dat out_iter\=00220_dist\=00.png 
e24b2da85210343c0828fbd1
```
_______
e34b2da852103c3c0828fbd1
e**2**4b2da852103**4**3c0828fbd1
_______

Is this expected behaviour that I don't understand? Do the two bytes not make a difference, somehow? Or is this only producing near-collisions instead of proper collisions?

**Comment by anishathalye** [comment]
Thank you for opening this issue.

A couple things contribute to the bug you described. One is that the optimization represents images with 32-bit floats per channel, whereas the saved image has 8 bits per channel. The adversarial example that is found is not necessarily "robust", so quantization could cause slight changes in the hash output. Another issue was that there was a bug in the code, where it did the gradient descent update step before saving the image, so the hash that as computed during the forward pass was not the hash of the saved image. These two issues should be fixed in 3cc3c19c61c50cd4d1e4666f71d47344d40d0173. With those changes, the issue is fixed with your example.

```console
$ python collide.py --image picard.png --target e34b2da852103c3c0828fbd1
...
iteration: 216/1000, best: 0, hash: e34b2da852103c3c0828fbd1, distance: 0, loss: 7.517
...
$ python nnhash.py out_iter=00216_dist=00.png
e34b2da852103c3c0828fbd1
```

![out_iter=00216_dist=00](https://user-images.githubusercontent.com/3526486/130319539-ded70170-37e9-4e60-a567-d035c2a572d1.png)

For more on the topic of robust adversarial examples, you could take a look at [this blog post](https://www.anishathalye.com/2017/07/25/synthesizing-adversarial-examples/) or [this paper](https://arxiv.org/abs/1707.07397). If I have some free time this weekend, I could try incorporating those techniques into this repo and maybe also address some of the other limitations [mentioned](https://github.com/anishathalye/neural-hash-collider#limitations) in the README.

**Comment by lambdaTotoro** [comment]
Can confirm, this has fixed the issue, I'll close it. Thanks for your swift and helpful reply! =)

**Comment by anishathalye** [comment]
By the way, I've implemented a couple of those techniques I mentioned above, so you can get a slightly nicer looking image now. See here for examples: https://github.com/anishathalye/neural-hash-collider#examples

**Comment by lambdaTotoro** [comment]
Very cool, thanks for the update!
